### ISSUE TITLE
Move save directory out of runtime into eve/saves

### ISSUE THREAD

**Issue by joshuafcole** [creativelive/spook#3]

**Comment by joshuafcole** [comment]
wrong repo!

**Comment by ryanjadhav** [comment]
:+1: should be scheduled for next release.

**Comment by diffsky** [comment]
I'm making it top priority, no matter what @joshuafcole says

**Comment by joshuafcole** [comment]
For reference, I'm spending the week getting integration testing in place for Eve.  Unfortunately, I tabbed to the wrong github page when logging a todo. I'm happy to see that the maintainers of this repository care so much about user's feature requests! ;)
